# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HalmeNjrPQevVmYnEtSW0g-zgkqZ65SH
"""



import streamlit as st

st.title("My Streamlit Website")

st.header("Hello, World!")

name = st.text_input("Enter your name:")
st.write(f"Hello, {name}!")

st.write("This is a simple website created with Streamlit.")
